import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./content/**/*.{md,mdx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "text-heading": "#0F172A",
        "text-body": "#475569",
        "background": "#f7f9fb",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "border-subtle": "#E5E7EB",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "on-surface-variant": "#434655",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        outline: "#737686",
        "outline-variant": "#c3c6d7",
        primary: "#004ac6",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "on-primary-container": "#eeefff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-primary": "#b4c5ff",
        secondary: "#1d4ed8",
        "on-secondary": "#ffffff",
        "secondary-container": "#4069f2",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#dce1ff",
        "secondary-fixed-dim": "#b7c4ff",
        "on-secondary-fixed": "#001551",
        "on-secondary-fixed-variant": "#0039b5",
        tertiary: "#8e3c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b54e00",
        "on-tertiary-container": "#ffece5",
        "tertiary-fixed": "#ffdbca",
        "tertiary-fixed-dim": "#ffb690",
        "on-tertiary-fixed": "#341100",
        "on-tertiary-fixed-variant": "#783200",
        "success-emerald": "#10B981",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "indigo-gradient-stop": "#4F46E5",
        "affiliate-start": "#F97316",
        "affiliate-end": "#EA580C",
      },
      spacing: {
        "unit-xs": "4px",
        "unit-sm": "8px",
        "unit-md": "16px",
        "unit-lg": "24px",
        "unit-xl": "48px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        headline: ["var(--font-geist-sans)", "Geist", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        "display-xl": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "headline-lg": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "headline-lg-mobile": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "headline-md": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "label-md": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "label-sm": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["60px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      boxShadow: {
        "card": "0 4px 6px -1px rgba(0, 0, 0, 0.05)",
        "card-hover": "0 10px 15px -3px rgba(37, 99, 235, 0.1)",
        "cta": "0 4px 14px 0 rgba(37, 99, 235, 0.39)",
        "cta-hover": "0 6px 20px rgba(37, 99, 235, 0.23)",
        "affiliate": "0 4px 6px -1px rgba(249, 115, 22, 0.3)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};

export default config;
